[general]
rest_server_port = "0.0.0.0:5000"

[auth]
password = "pass"
user = "user"

[dbcfg]
db_host = "localhost"
db_name = "plivo_cloud"
db_password = ""
db_user = "plivocfg"
db_port = "5432"
db_type = "postgres"
db_ssl_mode = "disable"